server:
  port: 5555

spring:
  cloud:
    config:
      server:
        git:
#          uri: file:///C:\git\Git_Repository\SimpleMSA # local git
          uri: https://github.com/yooseek/SimpleMSA #remote git
          default-label: main
#          username: [username]  # id
#          password: [password]  # password
  application:
    name: config-service
